Rename import&export scripts for consistency
* Drop .sh from autosync and autosync-mediawiki
* Rename autosync* to autoimport*
* Rename nike-export-all to autoexport
* Add autoexport-mediawiki to complement autoimport-mediawiki
* Fix findexportroot to look for repoconfig.yaml, REPOCONF is dead
* Shellscheck fixes

Now we have this nice set of easy to use scripts:
* autoimport (all \ mediawiki in gerrit)
* autoimport-mediawiki
* autoexport (all \ mediawiki in gerrit)
* autoexport-mediawiki

Reasons for separation is that Raimond still handles MediaWiki
while I (or someone else) does all the rest, including MediaWiki
extensions not hosted in Gerrit.

Change-Id: If518f556b1de8e9306755cac65c6f664eda2771f

diff --git a/bin/findexportroot b/bin/findexportroot
--- a/bin/findexportroot
+++ b/bin/findexportroot
@@ -1,20 +1,19 @@
-#!/bin/bash
+#!/bin/sh
 # Used by repo* scripts to find the repository root
 # similar to how like git tries to find .git
 
 while true
 do
-	if [ ! -f "$DIR/REPOCONF" ]
+	if [ ! -f "$DIR/repoconfig.yaml" ]
 	then
-		DIR=`dirname $DIR`
+		DIR=$(dirname "$DIR")
 	else
-		. "$DIR/REPOCONF"
 		break
 	fi
 
 	if [ "$DIR" = "/" ]
 	then
-		echo "Fatal: Could not find REPOCONF file"
-		exit 1;
+		echo "Fatal: Could not find repoconfig.yaml"
+		exit 1
 	fi
 done
