Retry when update-reset repo fails
This should address issues with "Permission denied (publickey).", as it doesn't
usually fail twice in a row for the same repo.

Change-Id: If866c8ceaeceadae5d31c51ba559fc8e665a15b4

diff --git a/bin/update-reset-repo b/bin/update-reset-repo
--- a/bin/update-reset-repo
+++ b/bin/update-reset-repo
@@ -15,6 +15,12 @@ OUTPUT=$(git fetch -q --all && git reset -q --hard origin/master && git clean -q
 CODE=$?
 
 if [ $CODE -ne 0 ]; then
-	printf "\033[31m%s failed to update\033[0m\n" "$DIR";
-	echo $OUTPUT;
+    cd $DIR
+    echo "Retry $DIR"
+    OUTPUT=$(git fetch -q --all && git reset -q --hard origin/master && git clean -q -f -d 2>&1 >&-)
+    CODE=$?
+    if [ $CODE -ne 0 ]; then
+        printf "\033[31m%s failed to update\033[0m\n" "$DIR";
+        echo $OUTPUT;
+    fi
 fi
