Update wiki update scripts
Change-Id: If6c6ef2ae9ba7f0430403e4a9e5ace702873aa93

diff --git a/bin/wikiupdate-repo b/bin/wikiupdate-repo
--- a/bin/wikiupdate-repo
+++ b/bin/wikiupdate-repo
@@ -1,12 +1,10 @@
 #!/bin/bash
-
-set -e
+set -o nounset -o pipefail -o errexit
 
 cd "$1"
-OUTPUT=$(git pull --quiet --rebase 2>&1 >&-; git submodule update --init)
-CODE=$?
-
-if [ $CODE -ne 0 ]; then
-	printf "\033[31m%s failed to update\033[0m\n" "$1"
+if ! OUTPUT=$(git pull --quiet --rebase 2>&1 >&- && git submodule update --init); then
+	CODE=$?
+	printf "\\033[31m%s failed to update\\033[0m\\n" "$1"
 	echo "$OUTPUT"
+	exit "$CODE"
 fi
