Update wikiupdate scripts to handle submodules
Springle bunch of shellcheck fixes on related scripts

Change-Id: I1e5360b35c8113559c6265b0999eda1ba0919579

diff --git a/bin/wikiupdate-repo b/bin/wikiupdate-repo
--- a/bin/wikiupdate-repo
+++ b/bin/wikiupdate-repo
@@ -1,10 +1,12 @@
 #!/bin/bash
 
-cd $1
-OUTPUT=$(git pull --quiet --rebase 2>&1 >&-)
+set -e
+
+cd "$1"
+OUTPUT=$(git pull --quiet --rebase 2>&1 >&-; git submodule update --init)
 CODE=$?
 
 if [ $CODE -ne 0 ]; then
-	printf "\033[31m%s failed to update\033[0m\n" "$1";
-	echo $OUTPUT;
+	printf "\033[31m%s failed to update\033[0m\n" "$1"
+	echo "$OUTPUT"
 fi
